# Generated by Django 4.0.4 on 2022-05-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_org_num',
            new_name='client_org_number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='is_send',
            new_name='is_sent',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='net_amout',
            new_name='net_amount',
        ),
    ]
