# Generated by Django 4.0.4 on 2022-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
