# Generated by Django 4.0.4 on 2022-05-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_is_credited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_credited',
        ),
    ]
